<?php

namespace SkiBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReviews($stationId)
    {
        return $this->createQueryBuilder('review')
                    ->andWhere('review.stationId = :stationid')
                    ->setParameter('stationid', $stationId)
                    ->getQuery()
                    ->execute();
    }
}
